### ISSUE TITLE
HDR textures with large values prevents the overlay text from being readable

### ISSUE THREAD

**Issue by nickludlam** [vertxxyz/NTexturePreview#13]
![Screenshot 2019-11-07 at 14 58 10](https://user-images.githubusercontent.com/7568/68995429-c5c64780-0885-11ea-8d7b-7abfc96906f1.png)

As can be seen in the image, if you have a float texture with large values, Unity doesn't seem to clamp the render values, which throws off alpha blending of the text overlays

**Comment by vertxxyz** [comment]
Should be fixed now, though this has brought up some interesting linear/gamma differences where I'm not sure what the picker is meant to be displaying. So if you or anyone else does sees any discrepancy that doesn't make sense and have any idea what it might be, let me know.
